<?php

$bowob_icones = Array(":)", ":d", ":p", ";)", ":(", ":'(", ":@", ":o", "(l)", "8|", ":s", "8)", ":/", ":|", ":*)");
$bowob_icones_path = Array("http://ursvisual.com/atrium2/sites/all/modules/bowob/bowob_theme_1/icon_1.gif", "http://ursvisual.com/atrium2/sites/all/modules/bowob/bowob_theme_1/icon_2.gif", "http://ursvisual.com/atrium2/sites/all/modules/bowob/bowob_theme_1/icon_3.gif", "http://ursvisual.com/atrium2/sites/all/modules/bowob/bowob_theme_1/icon_4.gif", "http://ursvisual.com/atrium2/sites/all/modules/bowob/bowob_theme_1/icon_5.gif", "http://ursvisual.com/atrium2/sites/all/modules/bowob/bowob_theme_1/icon_6.gif", "http://ursvisual.com/atrium2/sites/all/modules/bowob/bowob_theme_1/icon_7.gif", "http://ursvisual.com/atrium2/sites/all/modules/bowob/bowob_theme_1/icon_8.gif", "http://ursvisual.com/atrium2/sites/all/modules/bowob/bowob_theme_1/icon_9.gif", "http://ursvisual.com/atrium2/sites/all/modules/bowob/bowob_theme_1/icon_10.gif", "http://ursvisual.com/atrium2/sites/all/modules/bowob/bowob_theme_1/icon_11.gif", "http://ursvisual.com/atrium2/sites/all/modules/bowob/bowob_theme_1/icon_12.gif", "http://ursvisual.com/atrium2/sites/all/modules/bowob/bowob_theme_1/icon_13.gif", "http://ursvisual.com/atrium2/sites/all/modules/bowob/bowob_theme_1/icon_14.gif", "http://ursvisual.com/atrium2/sites/all/modules/bowob/bowob_theme_1/icon_15.gif");
$bowob_sounds_path = Array("http://ursvisual.com/atrium2/sites/all/modules/bowob/bowob_theme_1/sound_1.mp3", "http://ursvisual.com/atrium2/sites/all/modules/bowob/bowob_theme_1/sound_2.mp3", "http://ursvisual.com/atrium2/sites/all/modules/bowob/bowob_theme_1/sound_3.mp3", "http://ursvisual.com/atrium2/sites/all/modules/bowob/bowob_theme_1/sound_4.mp3");
$bowob_sounds_volume = 0;
$bowob_language_object = Array("usuario_guest", "menu_general", "menu_admin", "chat", "nuevo_mensaje", "negrita", "subrayado", "cursiva", "conexion_cargando", "conexion_error", "conexion_perdida", "me_expulsado", "me_nick_uso", "me_expulsado_floodear", "me_entrada_exterior", "me_expulsado", "me_flood_detectado", "ususario_entra", "ususario_sale", "ususario_sale_perdida", "ususario_expulsado_floodear", "ususario_expulsado", "ususario_no_conectado", "admin_cerrar", "admin_expulsar_nick", "admin_lista", "admin_anadir", "admin_guardar", "admin_nick", "admin_fecha", "admin_duracion", "admin_inmediata", "admin_temporal", "admin_permanente", "admin_meses", "admin_dias", "admin_horas", "admin_minutos", "admin_segundos", "admin_ver", "admin_eliminar", "admin_expulsar_ip", "admin_tipo", "admin_ip", "admin_ip_de_nick", "admin_admins", "admin_asunto");
$bowob_language = Array("Guest", "All Users", "Administration", "Chat", "New message chat", "B", "U", "I", "Loading ...", "Loading error", "Connection Lost", "Banned", "Username taken", "Banned (flood)", "Reload", "Banned", "Flood detected", "join", "quit", "quit (timeout)", "banned (flood)", "banned", "offline", "Close", "Kick Username", "List", "Add", "Save", "Username", "Date", "Time", "Immediate", "Temporary", "For ever", "Months", "Days", "Hours", "Minutes", "Seconds", "See", "Delete", "Kick Ip", "Type", "Ip", "Username Ip", "Admins", "Topic");

?>
